import numpy as np
MEMORY_LENGTH = 30000
memory = np.zeros((MEMORY_LENGTH), dtype=np.int8)
index = 0
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
while(memory[index]):
	index+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	index+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	index+=1
	memory[index]+=1
	memory[index]+=1
	memory[index]+=1
	index+=1
	memory[index]+=1
	index-=1
	index-=1
	index-=1
	index-=1
	memory[index]-=1
index+=1
memory[index]+=1
memory[index]+=1
print(chr(memory[index]), end="")
index+=1
memory[index]+=1
print(chr(memory[index]), end="")
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
print(chr(memory[index]), end="")
print(chr(memory[index]), end="")
memory[index]+=1
memory[index]+=1
memory[index]+=1
print(chr(memory[index]), end="")
index+=1
memory[index]+=1
memory[index]+=1
print(chr(memory[index]), end="")
index-=1
index-=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
memory[index]+=1
print(chr(memory[index]), end="")
index+=1
print(chr(memory[index]), end="")
memory[index]+=1
memory[index]+=1
memory[index]+=1
print(chr(memory[index]), end="")
memory[index]-=1
memory[index]-=1
memory[index]-=1
memory[index]-=1
memory[index]-=1
memory[index]-=1
print(chr(memory[index]), end="")
memory[index]-=1
memory[index]-=1
memory[index]-=1
memory[index]-=1
memory[index]-=1
memory[index]-=1
memory[index]-=1
memory[index]-=1
print(chr(memory[index]), end="")
index+=1
memory[index]+=1
print(chr(memory[index]), end="")
index+=1
print(chr(memory[index]), end="")
